# Generated by Django 4.2.4 on 2023-08-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
