# Generated by Django 4.2.4 on 2023-08-22 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='image',
            new_name='photo',
        ),
    ]
